#!/bin/bash

cd "$(dirname "$0")"/..

echo "Making sure directories exist..."

mkdir -p private private/files

cd private

echo "Generating key and self-signed certificate..."

openssl req \
  -x509 \
  -days 3650 \
  -newkey rsa:3072 \
  -nodes \
  -keyout key.pem \
  -out cert.pem \
  -subj "/CN=localhost/"

echo "Generated key and certificate"
