#!/bin/bash

cd "$(dirname "$0")"/..

python3 src/ptt/cli.py peer add foo
python3 src/ptt/cli.py peer connect foo

python3 src/ptt/cli.py peer send-text foo
python3 src/ptt/cli.py peer send-text foo
python3 src/ptt/cli.py peer send-text foo

python3 src/ptt/cli.py peer read-texts foo
